//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Payment
    {
        [DataMember]
        public int Payment_Id { get; set; }
        [DataMember]
        public string Payment_Type { get; set; }
        [DataMember]
        public string Payment_Status { get; set; }
        [DataMember]
        public string Payment_Amount { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
